using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Go_Singapore.Controllers
{
    public static class CountryMatcher
    {
        public static Dictionary<string, string> GetDictionary()
        {
            Dictionary<string, string> dict = new Dictionary<string, string>();
            dict.Add("AED", "United Arab Emirates");
            dict.Add("AFN", "Afghanistan");
            dict.Add("ALL", "Albania");
            dict.Add("AMD", "Armenia");
            dict.Add("ANG", "Netherlands Antilles");
            dict.Add("AOA", "Angola");
            dict.Add("ARS", "Argentina");
            dict.Add("AUD", "Australia, Australian Antarctic Territory, Christmas Island, Cocos (Keeling) Islands, Heard and McDonald Islands, Kiribati, Nauru, Norfolk Island, Tuvalu");
            dict.Add("AWG", "Aruba");
            dict.Add("AZN", "Azerbaijan");
            dict.Add("BAM", "Bosnia and Herzegovina");
            dict.Add("BBD", "Barbados");
            dict.Add("BDT", "Bangladesh");
            dict.Add("BGN", "Bulgaria");
            dict.Add("BHD", "Bahrain");
            dict.Add("BIF", "Burundi");
            dict.Add("BMD", "Bermuda");
            dict.Add("BND", "Brunei");
            dict.Add("BOB", "Bolivia");
            dict.Add("BOV", "Bolivia");
            dict.Add("BRL", "Brazil");
            dict.Add("BSD", "Bahamas");
            dict.Add("BTN", "Bhutan");
            dict.Add("BWP", "Botswana");
            dict.Add("BYR", "Belarus");
            dict.Add("BZD", "Belize");
            dict.Add("CAD", "Canada");
            dict.Add("CDF", "Democratic Republic of Congo");
            dict.Add("CHE", "Switzerland");
            dict.Add("CHF", "Switzerland, Liechtenstein");
            dict.Add("CHW", "Switzerland");
            dict.Add("CLF", "Chile");
            dict.Add("CLP", "Chile");
            dict.Add("CNY", "Mainland China");
            dict.Add("COP", "Colombia");
            dict.Add("COU", "Colombia");
            dict.Add("CRC", "Costa Rica");
            dict.Add("CUP", "Cuba");
            dict.Add("CVE", "Cape Verde");
            dict.Add("CYP", "Cyprus");
            dict.Add("CZK", "Czech Republic");
            dict.Add("DJF", "Djibouti");
            dict.Add("DKK", "Denmark, Faroe Islands, Greenland");
            dict.Add("DOP", "Dominican Republic");
            dict.Add("DZD", "Algeria");
            dict.Add("EEK", "Estonia");
            dict.Add("EGP", "Egypt");
            dict.Add("ERN", "Eritrea");
            dict.Add("ETB", "Ethiopia");
            dict.Add("EUR", "European Union, see eurozone");
            dict.Add("FJD", "Fiji");
            dict.Add("FKP", "Falkland Islands");
            dict.Add("GBP", "United Kingdom");
            dict.Add("GEL", "Georgia");
            dict.Add("GHS", "Ghana");
            dict.Add("GIP", "Gibraltar");
            dict.Add("GMD", "Gambia");
            dict.Add("GNF", "Guinea");
            dict.Add("GTQ", "Guatemala");
            dict.Add("GYD", "Guyana");
            dict.Add("HKD", "Hong Kong Special Administrative Region");
            dict.Add("HNL", "Honduras");
            dict.Add("HRK", "Croatia");
            dict.Add("HTG", "Haiti");
            dict.Add("HUF", "Hungary");
            dict.Add("IDR", "Indonesia");
            dict.Add("ILS", "Israel");
            dict.Add("INR", "Bhutan, India");
            dict.Add("IQD", "Iraq");
            dict.Add("IRR", "Iran");
            dict.Add("ISK", "Iceland");
            dict.Add("JMD", "Jamaica");
            dict.Add("JOD", "Jordan");
            dict.Add("JPY", "Japan");
            dict.Add("KES", "Kenya");
            dict.Add("KGS", "Kyrgyzstan");
            dict.Add("KHR", "Cambodia");
            dict.Add("KMF", "Comoros");
            dict.Add("KPW", "North Korea");
            dict.Add("KRW", "South Korea");
            dict.Add("KWD", "Kuwait");
            dict.Add("KYD", "Cayman Islands");
            dict.Add("KZT", "Kazakhstan");
            dict.Add("LAK", "Laos");
            dict.Add("LBP", "Lebanon");
            dict.Add("LKR", "Sri Lanka");
            dict.Add("LRD", "Liberia");
            dict.Add("LSL", "Lesotho");
            dict.Add("LTL", "Lithuania");
            dict.Add("LVL", "Latvia");
            dict.Add("LYD", "Libya");
            dict.Add("MAD", "Morocco, Western Sahara");
            dict.Add("MDL", "Moldova");
            dict.Add("MGA", "Madagascar");
            dict.Add("MKD", "Former Yugoslav Republic of Macedonia");
            dict.Add("MMK", "Myanmar");
            dict.Add("MNT", "Mongolia");
            dict.Add("MOP", "Macau Special Administrative Region");
            dict.Add("MRO", "Mauritania");
            dict.Add("MTL", "Malta");
            dict.Add("MUR", "Mauritius");
            dict.Add("MVR", "Maldives");
            dict.Add("MWK", "Malawi");
            dict.Add("MXN", "Mexico");
            dict.Add("MXV", "Mexico");
            dict.Add("MYR", "Malaysia");
            dict.Add("MZN", "Mozambique");
            dict.Add("NAD", "Namibia");
            dict.Add("NGN", "Nigeria");
            dict.Add("NIO", "Nicaragua");
            dict.Add("NOK", "Norway");
            dict.Add("NPR", "Nepal");
            dict.Add("NZD", "Cook Islands, New Zealand, Niue, Pitcairn, Tokelau");
            dict.Add("OMR", "Oman");
            dict.Add("PAB", "Panama");
            dict.Add("PEN", "Peru");
            dict.Add("PGK", "Papua New Guinea");
            dict.Add("PHP", "Philippines");
            dict.Add("PKR", "Pakistan");
            dict.Add("PLN", "Poland");
            dict.Add("PYG", "Paraguay");
            dict.Add("QAR", "Qatar");
            dict.Add("RON", "Romania");
            dict.Add("RSD", "Serbia");
            dict.Add("RUB", "Russia, Abkhazia, South Ossetia");
            dict.Add("RWF", "Rwanda");
            dict.Add("SAR", "Saudi Arabia");
            dict.Add("SBD", "Solomon Islands");
            dict.Add("SCR", "Seychelles");
            dict.Add("SDG", "Sudan");
            dict.Add("SEK", "Sweden");
            dict.Add("SGD", "Singapore");
            dict.Add("SHP", "Saint Helena");
            dict.Add("SKK", "Slovakia");
            dict.Add("SLL", "Sierra Leone");
            dict.Add("SOS", "Somalia");
            dict.Add("SRD", "Suriname");
            dict.Add("STD", "São Tomé and Príncipe");
            dict.Add("SYP", "Syria");
            dict.Add("SZL", "Swaziland");
            dict.Add("THB", "Thailand");
            dict.Add("TJS", "Tajikistan");
            dict.Add("TMM", "Turkmenistan");
            dict.Add("TND", "Tunisia");
            dict.Add("TOP", "Tonga");
            dict.Add("TRY", "Turkey");
            dict.Add("TTD", "Trinidad and Tobago");
            dict.Add("TWD", "Taiwan and other islands that are under the effective control of the Republic of China (ROC)");
            dict.Add("TZS", "Tanzania");
            dict.Add("UAH", "Ukraine");
            dict.Add("UGX", "Uganda");
            dict.Add("USD", "American Samoa, British Indian Ocean Territory, Ecuador, El Salvador, Guam, Haiti, Marshall Islands, Micronesia, Northern Mariana Islands, Palau, Panama, Puerto Rico, East Timor, Turks and Caicos Islands, United States, Virgin Islands");
            dict.Add("USN", "United States");
            dict.Add("USS", "United States");
            dict.Add("UYU", "Uruguay");
            dict.Add("UZS", "Uzbekistan");
            dict.Add("VEB", "Venezuela");
            dict.Add("VND", "Vietnam");
            dict.Add("VUV", "Vanuatu");
            dict.Add("WST", "Samoa");
            dict.Add("XAF", "Cameroon, Central African Republic, Congo, Chad, Equatorial Guinea, Gabon");
            dict.Add("XCD", "Anguilla, Antigua and Barbuda, Dominica, Grenada, Montserrat, Saint Kitts and Nevis, Saint Lucia, Saint Vincent and the Grenadines");
            dict.Add("XDR", "International Monetary Fund");
            dict.Add("XFO", "Bank for International Settlements");
            dict.Add("XFU", "International Union of Railways");
            dict.Add("XOF", "Benin, Burkina Faso, Côte d'Ivoire, Guinea-Bissau, Mali, Niger, Senegal, Togo");
            dict.Add("XPF", "French Polynesia, New Caledonia, Wallis and Futuna");
            dict.Add("YER", "Yemen");
            dict.Add("ZAR", "South Africa");
            dict.Add("ZMK", "Zambia");
            dict.Add("ZWD", "Zimbabwee");
            return dict;
        }
    }
}